on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Test on ${{ matrix.os }}
    steps:
      - name: Checks out a copy of your repository
        uses: actions/checkout@v1
      - name: Run tests
        run: ./tests/ansi.sh
        id: tests
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.tests.outputs.time }}.'
