name: Run tests
on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [bash, dash, ash, mksh]
    name: Ubuntu in ${{ matrix.shell }}
    steps:
      - name: Checks out a copy of your repository
        uses: actions/checkout@v2
      - name: Install ${{ matrix.shell }}
        run: sudo apt-get install ${{ matrix.shell }}
      - name: Run tests
        run: ${{ matrix.shell }} ./tests/ansi.sh

  alpine:
    runs-on: ubuntu-latest
    name: Alpine Linux
    steps:
      - name: Checks out a copy of your repository
        uses: actions/checkout@v2
      - name: Run sh
        run: docker run --rm -v "`pwd`:`pwd`" -w "`pwd`" alpine:latest sh ./tests/ansi.sh

  mac:
    runs-on: macOS-latest
    name: MacOS
    steps:
      - name: Checks out a copy of your repository
        uses: actions/checkout@v2
      - name: Run tests
        run: ./tests/ansi.sh

  windows:
    runs-on: windows-latest
    name: Windows
    steps:
      - name: Checks out a copy of your repository
        uses: actions/checkout@v2
      - name: Download busybox
        shell: powershell
        run: (New-Object Net.WebClient).DownloadFile('https://frippery.org/files/busybox/busybox.exe', 'busybox.exe')
      - name: Run tests
        shell: cmd
        run: busybox.exe sh ./tests/ansi.sh
